Removed necessity for hard-coding IPs of host
Fix for the TypeError
TypeError: 'module' object is not callable error happening because of call to pcap_to_ditg.
Removed necessity for hard-coding IPs of host
Clear a debug message